apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        imagePullPolicy: IfNotPresent
        image: "192.168.64.1:5000/postgres:11.5"
        ports:
        - name: postgresport
          containerPort: 5432
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 500Mi          
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: airflow
        - name: POSTGRES_DB
          value: airflow
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-db  
  volumeClaimTemplates:
  - metadata:
      name: postgres-db
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
      volumeName: "postgres-volume"
---
kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - name: postgresport
    protocol: TCP
    port: 5432
    targetPort: postgresport
  type: ClusterIP
